### ISSUE TITLE
Interface org.eclipse.lsp4j.jsonrpc.Endpoint is not visible from class loader

### ISSUE THREAD

**Issue by LucasBullen** [eclipse/lsp4j#121]
I am attempting to set up lsp4j to be used with lsp4e, however I receive the following error when starting the LS connection:
```
java.lang.IllegalArgumentException: interface org.eclipse.lsp4j.jsonrpc.Endpoint is not visible from class loader
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.toServiceObject(ServiceEndpoints.java:32)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createIoLauncher(Launcher.java:151)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createIoLauncher(Launcher.java:112)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createLauncher(Launcher.java:94)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.start(ProjectSpecificLanguageServerWrapper.java:172)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.connect(ProjectSpecificLanguageServerWrapper.java:285)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor(LanguageServiceAccessor.java:262)
	at org.eclipse.lsp4e.outline.EditorToOutlineAdapterFactory.getAdapter(EditorToOutlineAdapterFactory.java:34)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:335)
	at org.eclipse.core.internal.runtime.AdapterManager.loadAdapter(AdapterManager.java:362)
	at org.eclipse.core.runtime.Adapters.queryAdapterManager(Adapters.java:113)
	...
```

Any suggestions on what I am missing to begin working on lsp4j?

**Comment by kittaakos** [comment]
You can find an example for the YANG language [here](https://github.com/yang-tools). I hope this helps.

**Comment by LucasBullen** [comment]
Need more guidance from that.

I am using Eclipse, have the lsp4e project and a [language server project](https://github.com/eclipselabs/language-servers-for-eclipse/tree/master/org.eclipse.lsp4e.php) open. Everything works as expected. Then I use [BuildShip](https://projects.eclipse.org/projects/tools.buildship) to import the lsp4j project instead of using the snapshot and then I begin receiving the above error.

Does that better explain my problem?

**Comment by mickaelistria** [comment]
This happens only when you're in dev mode (ie with LSP4J bundles loaded in your workspace), right?
If you have the LSP4J bundles in your target-platform, it's all fine?

**Comment by LucasBullen** [comment]
Correct

**Comment by spoenemann** [comment]
The MANIFEST.MF files are not checked into the git repo, but are generated during the Gradle build. There is a task that copies the generated manifests into the META-INF folders of each project:
```
./gradlew eclipseManifest
```

**Comment by LucasBullen** [comment]
That was the issue, thank you for the help.
