### ISSUE TITLE
ClassCastException in  org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(NotificationMessage)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/lsp4j#14]
i am getting this ClassCastException in org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(NotificationMessage)

```
Nov 21, 2016 2:51:34 PM org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor run
SCHWERWIEGEND: java.lang.Double cannot be cast to java.lang.String
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:154)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:124)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by cdietrich** [comment]
Here is the message

```
{
  "method": "$/cancelRequest",
  "params": {
    "id": 2.0
  },
  "jsonrpc": "2.0"
}
```

**Comment by cdietrich** [comment]
updating the latest changes helped
