### ISSUE TITLE
Exceptions during invocation of proxy methods not flowing back to client in CompleteableFuture

### ISSUE THREAD

**Issue by jonahkichwacoders** [eclipse/lsp4j#144]
All the JsonRPC calls are supposed to return a `CompleteableFuture`, however there are failure paths that don't return a `CompleteableFuture`. This means that you end up needing to double up the exception handling for what ought to be checked exceptions.

For example, consider this stack trace for what I am working on. In the middle of a call the remote end disappears. If it disappears before the `RemoteEndpoint.request` an `IOException` is passed to the rpc caller (wrapped in a `RuntimeException`). However if the exception happens further in the processing, a `CompleteableFuture` is returned that can have an `exceptionally` stage added to it for exception handling. Since I generally need the `exceptionally`, avoiding the extra try/catch would be nicer.

```
java.lang.RuntimeException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:68)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:51)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:138)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:77)
	at com.sun.proxy.$Proxy21.disconnect(Unknown Source)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.terminate(DSPDebugTarget.java:253)
	at org.eclipse.debug.internal.core.commands.TerminateCommand.execute(TerminateCommand.java:32)
	at org.eclipse.debug.internal.core.commands.ForEachCommand.doExecute(ForEachCommand.java:32)
	at org.eclipse.debug.core.commands.AbstractDebugCommand$1.run(AbstractDebugCommand.java:225)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:65)
```

**Comment by jonahkichwacoders** [comment]
What I recommend is that `RemoteEndpoint.request` returns the `CompletableFuture` in the already exceptionally completed state, for example like this.
```
diff --git a/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/RemoteEndpoint.java b/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/RemoteEndpoint.java
index 410bf15..0558dd9 100644
--- a/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/RemoteEndpoint.java
+++ b/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/RemoteEndpoint.java
@@ -135,7 +135,11 @@
 		synchronized(sentRequestMap) {
 			sentRequestMap.put(id, new PendingRequestInfo(requestMessage, responseHandler));
 		}
-		out.consume(requestMessage);
+		try {
+			out.consume(requestMessage);
+		} catch (RuntimeException e) {
+			result.completeExceptionally(e);
+		}
 		return result;
 	}
 
```

If that sounds like a reasonable approach I will put together a proper patch/tests.

**Comment by spoenemann** [comment]
👍

**Comment by spoenemann** [comment]
I'll work on this together with #152.
