### ISSUE TITLE
Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $

### ISSUE THREAD

**Issue by mniewrzal** [eclipse/lsp4j#17]
I have exception after completion request. Result JSON looks like this: 
```json
{
	"result": [
		{
			"label": "methodXXX",
			"kind": 2,
			"detail": "\\B",
			"documentation": null,
			"sortText": null,
			"filterText": null,
			"insertText": null,
			"textEdit": null,
			"additionalTextEdits": null,
			"command": null,
			"data": null
		}
	],
	"id": "29",
	"jsonrpc": "2.0"
}
```
Stacktrace:
```
Nov 24, 2016 12:10:21 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: Could not parse response: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
org.eclipse.lsp4j.jsonrpc.json.InvalidMessageException: Could not parse response: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseResponse(MessageJsonHandler.java:127)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:71)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:60)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:148)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.fromJson(MessageJsonHandler.java:102)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseResponse(MessageJsonHandler.java:118)
	... 10 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:87)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 14 more
```

**Comment by spoenemann** [comment]
We used to have special handling of arrays in the result objects. @svenefftinge could it be that your change a98b0a9 causes this issue?

**Comment by mniewrzal** [comment]
Server was using `CompletionItem[]` instead of `CompletionList`. As far I understand array version is not supported. Closing.

**Comment by mniewrzal** [comment]
I noticed the same problem with method `textDocument/hover` response:
```json
{
	"jsonrpc": "2.0",
	"id": "41",
	"result": {
		"contents": [
			{
				"language": "html",
				"value": "<body>"
			},
			"The body element represents the content of the document\\."
		],
		"range": {
			"start": {
				"line": 1,
				"character": 3
			},
			"end": {
				"line": 1,
				"character": 7
			}
		}
	}
}
```
```
Dec 05, 2016 1:17:06 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: Could not parse response: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.contents[0]
org.eclipse.lsp4j.jsonrpc.json.InvalidMessageException: Could not parse response: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.contents[0]
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseResponse(MessageJsonHandler.java:128)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:72)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:61)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:148)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.contents[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.fromJson(MessageJsonHandler.java:103)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseResponse(MessageJsonHandler.java:119)
	... 10 more
Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.contents[0]
	at com.google.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:180)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:418)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:406)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:78)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:54)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	... 14 more
```

**Comment by svenefftinge** [comment]
I added support for union types in the protocol, through the Either type.
We have to make use of it to close this :)

**Comment by mniewrzal** [comment]
> I added support for union types in the protocol, through the Either type in 2690093
> We have to make use of it to close this :)

@svenefftinge Can you give me any example how Either type can be used? I can help with adding this to protocol but all my experiments to utilize this type ends without success :)

**Comment by svenefftinge** [comment]
Thank you! I guess showing how the Either type should be used is best done by just doing the change :) 
We will put out an 0.1.0 release today or tomorrow and add the protocol changes to the new 0.2.0-SNAPSHOT stream afterwards. Xtext relies on LSP4J and is going to have a release in three weeks. It's a little late in the game to migrate to these changes. At least we want to be able to easily go back to the currently working state.

**Comment by mniewrzal** [comment]
Ok, I will wait for 'official' example :)
