### ISSUE TITLE
parseMessage Exception

### ISSUE THREAD

**Issue by liuyangc3** [eclipse/lsp4j#176]
I use monaco as client, it runs ok with node-languague-server,
recently our team use java instead of typescript to write lsp server. 
server can not parse request.

here is client request
```js
Content-Length: 1093

{"jsonrpc":"2.0","id":0,"method":"initialize","params":{
  "rootPath":null,
  "rootUri":null,
  "capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true},"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true}},"textDocument":{"synchronization":{"dynamicRegistration":true},"completion":{"completionItem":{"snippetSupport":true},"dynamicRegistration":true},"hover":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true}}},"trace":"off"}}

```
server Exception
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:899) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar:?]
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:78) ~[org.eclipse.lsp4j.jsonrpc-0.3.0.jar:?]
```

```java
```

**Comment by spoenemann** [comment]
I cannot reproduce this. Looking at the error message I assume that the message was incomplete, e.g. the first opening brace `{` was skipped. Could you check whether the full message is received in `MessageJsonHandler.parseMessage()`?

Otherwise, please wait for the LSP4J 0.4.0 release (end of this month) and reopen this issue if it still occurs with the new version.
