### ISSUE TITLE
Expected NAME but was NULL at path $.items[0].documentation

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#192]
From the php-language-server, I receive
```
{"result":{"isIncomplete":true,"items":[{"label":"$key","kind":6,"detail":"string","documentation":null,"sortText":null,"filterText":null,"insertText":null,"textEdit":{"range":{"start":{"line":23,"character":61},"end":{"line":23,"character":61}},"newText":"y"},"additionalTextEdits":null,"command":null,"data":null}]},"id":"3","jsonrpc":"2.0"}
```
and LSP4J 0.4.1 sends an exception when receiving the message. With a breakpoint and drilling down in the causes of the exception, I can finally see the cause:
```
java.lang.IllegalStateException: Expected NAME but was NULL at path $.items[0].documentation
```

As far as I understand from the spec, this error shouldn't show up as null is a valid value for the `documentation` node, and it seems to me -but without much certainity- that this is probably a bug in LSP4J.

**Comment by jabby** [comment]
Hello,
I faced the same issue on bluesky with the vscode html language server 1.24.
Here is the error when I try completion in `<style>|</style>` tag.
````
java.lang.IllegalStateException: Expected a name but was NULL at line 1 column 31928 path $.result.items[99].documentation
````

**Comment by jabby** [comment]
Here is the message I get from the html language server.

[html-css-completion.zip](https://github.com/eclipse/lsp4j/files/2102356/html-css-completion.zip)

**Comment by mickaelistria** [comment]
I've done more tests with LSP4J 0.4.1 and HTML language server, receiving ~360 completion items, and the error I get is a `MessageIssueException: Message could not be parsed." and the inner exception is `com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a name but was NULL at line 1 column 33022 path $.result.items[104].documentation`. I looked inside the message, and the 105th element is the first one of the sequence that shows `"documentation":null`.
So the same issue with 2 different LS drive to a similar case and this happens in LSP4E independently of whether log is enabled or not. Other completion requests on the same file at other locations where we don't have a `"documentation":null` just work and return a good response parsed and forwarded by LSP4J to LSP4E.
There seems to be something definitely wrong with parsing `"documentation":null` in some cases. I'll try to refine it.

**Comment by mickaelistria** [comment]
Here is the stack trace that's at the origin of it all:
```
java.lang.IllegalStateException: Expected a name but was NULL at line 1 column 33022 path $.result.items[104].documentation
	at com.google.gson.stream.JsonReader.nextName(JsonReader.java:789)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.read(CollectionTypeAdapter.java:110)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.read(CollectionTypeAdapter.java:36)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter$EitherTypeArgument.read(EitherTypeAdapter.java:138)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.create(EitherTypeAdapter.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.read(EitherTypeAdapter.java:72)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.read(EitherTypeAdapter.java:29)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.fromJson(MessageTypeAdapter.java:298)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.parseResult(MessageTypeAdapter.java:174)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:119)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:51)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:113)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:108)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by mickaelistria** [comment]
I think EitherTypeAdapter misses a in.nextNull() on line 69, which keeps a null token in the stack and fails further parsing.

**Comment by jonahgraham** [comment]
@mickaelistria your analysis looks right. Do you want to provide patch (including test), I can review/merge it

**Comment by jonahgraham** [comment]
:-) I see you are in progress, thanks to GitHub xrefs!

**Comment by mickaelistria** [comment]
@jonahgraham Thanks for following this closely! Indeed, #205 should fix it.

**Comment by jonahgraham** [comment]
I had a review through some of the other type adapters. All of them have a similar pattern of checking null first. In addition to the either adapter forgetting to consume the null, the throwable adapter also forgets. So I'll keep this open until that one is fixed too.

**Comment by jonahgraham** [comment]
PR #206 makes the same fix for Throwable adapter factory and adds a bunch of null test, for parsing and serializing.

**Comment by jabby** [comment]
@mickaelistria @jonahgraham 
Thanks for your work.
