### ISSUE TITLE
Version conflict with Guava 

### ISSUE THREAD

**Issue by fwcd** [eclipse/lsp4j#201]
There seems to be a strange runtime incompatibility between transitive Guava versions, because although my code compiles fine, it issues several `NoSuchMethodError`s at runtime:

```java
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	...
```

I am using LSP4J 0.4.1 and am not including Guava explicitly in my `build.gradle`:

```gradle
implementation "org.gradle:gradle-tooling-api:4.3"
implementation "org.eclipse.lsp4j:org.eclipse.lsp4j:0.4.1"
testImplementation "org.openjdk.jmh:jmh-core:1.20"
testImplementation "org.hamcrest:hamcrest-all:1.3"
testImplementation "junit:junit:4.10"
compileOnly "org.openjdk.jmh:jmh-generator-annprocess:1.20"
```

Dependency insight for Guava:

```gradle
com.google.guava:guava:21.0
   variant "runtime" [
      Requested attributes not found in the selected variant:
         org.gradle.usage = java-api
   ]

com.google.guava:guava:[14.0,22) -> 21.0
   variant "runtime" [
      Requested attributes not found in the selected variant:
         org.gradle.usage = java-api
   ]
\--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0
     +--- org.eclipse.xtend:org.eclipse.xtend.lib:2.14.0
     |    \--- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.4.1
     |         \--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.4.1
     |              \--- compileClasspath
     \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.14.0
          \--- org.eclipse.xtend:org.eclipse.xtend.lib:2.14.0 (*)

(*) - dependencies omitted (listed previously)
```

Dependency trees:

```gradle
compileClasspath - Compile classpath for source set 'main'.
+--- org.openjdk.jmh:jmh-generator-annprocess:1.20
|    \--- org.openjdk.jmh:jmh-core:1.20
|         +--- net.sf.jopt-simple:jopt-simple:4.6
|         \--- org.apache.commons:commons-math3:3.2
+--- org.gradle:gradle-tooling-api:4.3
|    \--- org.slf4j:slf4j-api:1.7.10
\--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.4.1
     +--- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.4.1
     |    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1
     |    |    \--- com.google.code.gson:gson:2.7
     |    \--- org.eclipse.xtend:org.eclipse.xtend.lib:[2.11.0,3) -> 2.14.0
     |         +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0
     |         |    \--- com.google.guava:guava:[14.0,22) -> 21.0
     |         \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.14.0
     |              \--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0 (*)
     \--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1 (*)

compileOnly - Compile only dependencies for source set 'main'.
\--- org.openjdk.jmh:jmh-generator-annprocess:1.20
     \--- org.openjdk.jmh:jmh-core:1.20
          +--- net.sf.jopt-simple:jopt-simple:4.6
          \--- org.apache.commons:commons-math3:3.2

default - Configuration for default artifacts.
+--- org.gradle:gradle-tooling-api:4.3
|    \--- org.slf4j:slf4j-api:1.7.10
\--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.4.1
     +--- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.4.1
     |    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1
     |    |    \--- com.google.code.gson:gson:2.7
     |    \--- org.eclipse.xtend:org.eclipse.xtend.lib:[2.11.0,3) -> 2.14.0
     |         +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0
     |         |    \--- com.google.guava:guava:[14.0,22) -> 21.0
     |         \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.14.0
     |              \--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0 (*)
     \--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1 (*)

implementation - Implementation only dependencies for source set 'main'. (n)
+--- org.gradle:gradle-tooling-api:4.3 (n)
+--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.4.1 (n)
+--- unspecified (n)
\--- unspecified (n)

runtimeClasspath - Runtime classpath of source set 'main'.
+--- org.gradle:gradle-tooling-api:4.3
|    \--- org.slf4j:slf4j-api:1.7.10
\--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.4.1
     +--- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.4.1
     |    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1
     |    |    \--- com.google.code.gson:gson:2.7
     |    \--- org.eclipse.xtend:org.eclipse.xtend.lib:[2.11.0,3) -> 2.14.0
     |         +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0
     |         |    \--- com.google.guava:guava:[14.0,22) -> 21.0
     |         \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.14.0
     |              \--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0 (*)
     \--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1 (*)

testCompileClasspath - Compile classpath for source set 'test'.
+--- org.gradle:gradle-tooling-api:4.3
|    \--- org.slf4j:slf4j-api:1.7.10
+--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.4.1
|    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.4.1
|    |    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1
|    |    |    \--- com.google.code.gson:gson:2.7
|    |    \--- org.eclipse.xtend:org.eclipse.xtend.lib:[2.11.0,3) -> 2.14.0
|    |         +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0
|    |         |    \--- com.google.guava:guava:[14.0,22) -> 21.0
|    |         \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.14.0
|    |              \--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0 (*)
|    \--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1 (*)
+--- org.openjdk.jmh:jmh-core:1.20
|    +--- net.sf.jopt-simple:jopt-simple:4.6
|    \--- org.apache.commons:commons-math3:3.2
+--- org.hamcrest:hamcrest-all:1.3
\--- junit:junit:4.10
     \--- org.hamcrest:hamcrest-core:1.1

testImplementation - Implementation only dependencies for source set 'test'. (n)
+--- org.openjdk.jmh:jmh-core:1.20 (n)
+--- org.hamcrest:hamcrest-all:1.3 (n)
\--- junit:junit:4.10 (n)

testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.gradle:gradle-tooling-api:4.3
|    \--- org.slf4j:slf4j-api:1.7.10
+--- org.eclipse.lsp4j:org.eclipse.lsp4j:0.4.1
|    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.generator:0.4.1
|    |    +--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1
|    |    |    \--- com.google.code.gson:gson:2.7
|    |    \--- org.eclipse.xtend:org.eclipse.xtend.lib:[2.11.0,3) -> 2.14.0
|    |         +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0
|    |         |    \--- com.google.guava:guava:[14.0,22) -> 21.0
|    |         \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.14.0
|    |              \--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.14.0 (*)
|    \--- org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc:0.4.1 (*)
+--- org.openjdk.jmh:jmh-core:1.20
|    +--- net.sf.jopt-simple:jopt-simple:4.6
|    \--- org.apache.commons:commons-math3:3.2
+--- org.hamcrest:hamcrest-all:1.3
\--- junit:junit:4.10
     \--- org.hamcrest:hamcrest-core:1.1

(*) - dependencies omitted (listed previously)

(n) - Not resolved (configuration is not meant to be resolved)
```

For reference, [I have had this issue previously](https://github.com/fwcd/KotlinLanguageServer/issues/2) and solved it by packaging my dependencies externally instead of creating a "fat jar". This - however - does not fix the issue anymore.

**Comment by fwcd** [comment]
I suspect this issue to be related to #191 although I am not using Maven.

**Comment by fwcd** [comment]
Closing this as this is not an issue with LSP4J - instead there was a compiled version of Guava that was bundled with a JAR dependency which Gradle did not recognize and thus conflicted with LSP4J's Guava.
