### ISSUE TITLE
"Duplicate RPC method threads" exception in DSPLauncher

### ISSUE THREAD

**Issue by fwcd** [eclipse/lsp4j#224]
I am currently creating an implementation of the Debug Adapter Protocol in Kotlin and having some trouble getting the `DSPLauncher` to run.

Stacktrace:

```
Exception in thread "main" java.lang.IllegalStateException: Duplicate RPC method threads.
        at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.lambda$getSupportedMethods$0(ServiceEndpoints.java:97)
        at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:62)
        at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:83)
        at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:75)
        at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:336)
        at org.eclipse.lsp4j.jsonrpc.debug.DebugLauncher$Builder.createJsonHandler(DebugLauncher.java:198)
        at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:271)
        at org.eclipse.lsp4j.jsonrpc.debug.DebugLauncher.createLauncher(DebugLauncher.java:59)
        at org.eclipse.lsp4j.debug.launch.DSPLauncher.createServerLauncher(DSPLauncher.java:39)
        at com.fwcd.ktda.KotlinDebugAdapterMainKt.main(KotlinDebugAdapterMain.kt:10)
```

Main function:
```kotlin
fun main(args: Array<String>) {
	val debugAdapter = KotlinDebugAdapter()
	val input = ExitingInputStream(System.`in`)
	val output = System.out
	val launcher = DSPLauncher.createServerLauncher(debugAdapter, input, output)
	
	debugAdapter.connect(launcher.remoteProxy)
	launcher.startListening()
}
```

`KotlinDebugAdapter` is a skeletal implementation of `IDebugProtocolServer` and `ExitingInputStream` is simply a wrapper around an existing `InputStream`.

**Comment by jonahgraham** [comment]
I'll take this for a spin tomorrow to see if I can reproduce (outside Kotlin). IIRC that error message means that you have two methods called `threads` both with the `@JsonRequest` and/or `@JsonNotification` annotations. Can you point me at your skeletal `KotlinDebugAdapter`? I am not that familiar with Kotlin, can Kotlin create multiple methods in the class file from single source method? I assume that `KotlinDebugAdapter` is written in Kotlin. Can you reproduce with `KotlinDebugAdapter` written in Java?

**Comment by fwcd** [comment]
@jonahgraham AFAIK, Kotlin does not work any different in this respect than Java (at least not when there are no Kotlin-only features like top-level functions or reified generics involved).

This is my current implementation of `KotlinDebugAdapter` (The `TODO`-method just throws an exception):

```kotlin
class KotlinDebugAdapter: IDebugProtocolServer {
	@JsonRequest
	override fun initialize(args: InitializeRequestArguments): CompletableFuture<Capabilities> {
		val capabilities = Capabilities()
		// TODO
		return completedFuture(capabilities)
	}
	
	fun connect(client: IDebugProtocolClient) {
		// TODO: Add client hooks here
	}
	
	@JsonRequest
	override fun runInTerminal(args: RunInTerminalRequestArguments): CompletableFuture<RunInTerminalResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun configurationDone(args: ConfigurationDoneArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun launch(args: Map<String, Any>): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun attach(args: Map<String, Any>): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun restart(args: RestartArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun disconnect(args: DisconnectArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun setBreakpoints(args: SetBreakpointsArguments): CompletableFuture<SetBreakpointsResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun setFunctionBreakpoints(args: SetFunctionBreakpointsArguments): CompletableFuture<SetFunctionBreakpointsResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun setExceptionBreakpoints(args: SetExceptionBreakpointsArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest(value = "continue")
	override fun continue_(args: ContinueArguments): CompletableFuture<ContinueResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun next(args: NextArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun stepIn(args: StepInArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun stepOut(args: StepOutArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun stepBack(args: StepBackArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun reverseContinue(args: ReverseContinueArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun restartFrame(args: RestartFrameArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest(value = "goto")
	override fun goto_(args: GotoArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun pause(args: PauseArguments): CompletableFuture<Void> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun stackTrace(args: StackTraceArguments): CompletableFuture<StackTraceResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun scopes(args: ScopesArguments): CompletableFuture<ScopesResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun variables(args: VariablesArguments): CompletableFuture<VariablesResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun setVariable(args: SetVariableArguments): CompletableFuture<SetVariableResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun source(args: SourceArguments): CompletableFuture<SourceResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun threads(): CompletableFuture<ThreadsResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun modules(args: ModulesArguments): CompletableFuture<ModulesResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun loadedSources(args: LoadedSourcesArguments): CompletableFuture<LoadedSourcesResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun evaluate(args: EvaluateArguments): CompletableFuture<EvaluateResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun stepInTargets(args: StepInTargetsArguments): CompletableFuture<StepInTargetsResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun gotoTargets(args: GotoTargetsArguments): CompletableFuture<GotoTargetsResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun completions(args: CompletionsArguments): CompletableFuture<CompletionsResponse> {
		TODO("not implemented yet")
	}
	
	@JsonRequest
	override fun exceptionInfo(args: ExceptionInfoArguments): CompletableFuture<ExceptionInfoResponse> {
		TODO("not implemented yet")
	}
}
```

**Comment by jonahgraham** [comment]
@fwcd I added an explicit [new test](https://github.com/eclipse/lsp4j/blob/bf0c6d2c5fc767e4130691631104917b470069f9/org.eclipse.lsp4j.debug/src/test/java/org/eclipse/lsp4j/debug/test/DSPDebugServer.java#L41) the replicates approximately what you are doing. Perhaps you can use that as a basis for making a test that fails. 

One thing that occurred to me as I wrote the test, are you adding duplicate `@JsonRequest` annotations in your `KotlinDebugAdpater`?

**Comment by jonahgraham** [comment]
OK, you are doing it differently for debug than how you did it for [LSP](https://github.com/fwcd/KotlinLanguageServer/blob/fedeada67025b21cae13306ed6108f5f8352e64b/src/main/kotlin/org/javacs/kt/KotlinLanguageServer.kt#L39). Remove the duplicate `@JSonRequest`s

**Comment by fwcd** [comment]
@jonahgraham This was the solution. I just copied the interface declaration from `IDebugProtocolServer` and did not remove the annotations. Thank you!
