### ISSUE TITLE
lsp4j.jsonrpc cannot be placed in an osgi container with gson dep

### ISSUE THREAD

**Issue by robstryker** [eclipse/lsp4j#251]
Putting gson-2.8.5.jar and org.eclipse.lsp4j.jsonrpc-0.4.1.jar into an apache felix installation errors in the following fashion:

ERROR: Bundle org.eclipse.lsp4j.jsonrpc [8] Error starting file:/home/rob/tmp/osgi1/felix-framework-6.0.1/bundle/org.eclipse.lsp4j.jsonrpc-0.4.1.jar (org.osgi.framework.BundleException: Unable to resolve org.eclipse.lsp4j.jsonrpc [8](R 8.0): missing requirement [org.eclipse.lsp4j.jsonrpc [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=com.google.gson.internal.bind) Unresolved requirements: [[org.eclipse.lsp4j.jsonrpc [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=com.google.gson.internal.bind)])
org.osgi.framework.BundleException: Unable to resolve org.eclipse.lsp4j.jsonrpc [8](R 8.0): missing requirement [org.eclipse.lsp4j.jsonrpc [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=com.google.gson.internal.bind) Unresolved requirements: [[org.eclipse.lsp4j.jsonrpc [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=com.google.gson.internal.bind)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4362)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2277)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1535)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:844)

lsp4j.jsonrpc imports several internal (non-exported) packages from the gson library.  This prevents the lsp4j.jsonrpc bundle from being installed. 

Script to demonstrate it:

``wget http://www.trieuvan.com/apache//felix/org.apache.felix.main.distribution-6.0.1.tar.gz
tar xvzf org.apache.felix.main.distribution-6.0.1.tar.gz
cd felix-framework-6.0.1/
cd bundle
wget http://central.maven.org/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar

# cd ../
# java -jar bin/felix.jar
# note that the framework starts fine
# cd bundle

wget http://central.maven.org/maven2/org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc/0.4.1/org.eclipse.lsp4j.jsonrpc-0.4.1.jar

cd ../
java -jar bin/felix.jar

# Note that there is an error

**Comment by spoenemann** [comment]
LSP4J uses Gson 2.7. Is the problem the same with that version?

**Comment by robstryker** [comment]
Yes, it is. 

```
wget http://www.trieuvan.com/apache//felix/org.apache.felix.main.distribution-6.0.1.tar.gz
tar xvzf org.apache.felix.main.distribution-6.0.1.tar.gz
cd felix-framework-6.0.1/
cd bundle
wget http://central.maven.org/maven2/com/google/code/gson/gson/2.7/gson-2.7.jar

# cd ../
# java -jar bin/felix.jar
# note that the framework starts fine
# cd bundle

wget http://central.maven.org/maven2/org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc/0.4.1/org.eclipse.lsp4j.jsonrpc-0.4.1.jar

cd ../
java -jar bin/felix.jar

# Note that there is an error
```

**Comment by robstryker** [comment]
Sorry, forgot the error
```
ERROR: Bundle org.eclipse.lsp4j.jsonrpc [8] Error starting file:/home/rob/tmp/osgi1/felix-framework-6.0.1/bundle/org.eclipse.lsp4j.jsonrpc-0.4.1.jar (org.osgi.framework.BundleException: Unable to resolve org.eclipse.lsp4j.jsonrpc [8](R 8.0): missing requirement [org.eclipse.lsp4j.jsonrpc [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=com.google.gson.internal.bind) Unresolved requirements: [[org.eclipse.lsp4j.jsonrpc [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=com.google.gson.internal.bind)])
org.osgi.framework.BundleException: Unable to resolve org.eclipse.lsp4j.jsonrpc [8](R 8.0): missing requirement [org.eclipse.lsp4j.jsonrpc [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=com.google.gson.internal.bind) Unresolved requirements: [[org.eclipse.lsp4j.jsonrpc [8](R 8.0)] osgi.wiring.package; (osgi.wiring.package=com.google.gson.internal.bind)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4362)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2277)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1535)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
