### ISSUE TITLE
Default SemanticHighlightingTokens implementation throws IAE 

### ISSUE THREAD

**Issue by dhuebner** [eclipse/lsp4j#278]
Using Xtext 2.16.0 and LSP4j 0.5.0

With the default binding for the SemanticHighlighting stuff I noticed that an IAE is thrown. Happens for example when opening a file by double-clicking an issue in a  "problems view"

I'm not sure if its an LSP4j issue or xtext.ide   

```
java.lang.IllegalArgumentException: Expected: 'scope' >= 0. 'scope' was: -1.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at org.eclipse.lsp4j.util.SemanticHighlightingTokens$Token.assertUint16(SemanticHighlightingTokens.java:196)
	at org.eclipse.lsp4j.util.SemanticHighlightingTokens$Token.<init>(SemanticHighlightingTokens.java:187)
	at org.eclipse.xtext.ide.server.semanticHighlight.SemanticHighlightingRegistry.lambda$toSemanticHighlightingInformation$9(SemanticHighlightingRegistry.java:303)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.xtext.ide.server.semanticHighlight.SemanticHighlightingRegistry.toSemanticHighlightingInformation(SemanticHighlightingRegistry.java:326)
	at org.eclipse.xtext.ide.server.semanticHighlight.SemanticHighlightingRegistry.update(SemanticHighlightingRegistry.java:282)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$null$62(LanguageServerImpl.java:1115)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$null$0(LanguageServerImpl.java:1059)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:283)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$doRead$1(LanguageServerImpl.java:1061)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kittaakos** [comment]
> opening a file by double-clicking an issue in a "problems view"

In Theia.

**Comment by cdietrich** [comment]
its and xtext bug. see getIndex in the registry

**Comment by kittaakos** [comment]
Closing in favor of https://github.com/eclipse/xtext-core/issues/924.
