### ISSUE TITLE
LSP4J fails for empty `definition` response.

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#308]
With LSP4J 0.7.0.
Is the response for `definition` is an empty list, then this stack trace is shown (and cause future to not complete):

```
SEVERE: Ambiguous Either type: token BEGIN_ARRAY matches both alternatives.
com.google.gson.JsonParseException: Ambiguous Either type: token BEGIN_ARRAY matches both alternatives.
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.create(EitherTypeAdapter.java:178)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.read(EitherTypeAdapter.java:162)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.read(EitherTypeAdapter.java:39)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.parseResult(MessageTypeAdapter.java:180)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:123)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:55)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:119)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:191)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
```

I think the EitherTypeAdapter should be improved to support the case of both types being collections and input being empty and/or the `definition` method return type should be change from `Either<List<Location>, List<LocationLink>>` to `List<Either<Location, LocationLink>>` (which by the way would be easier to process on client side).

**Comment by spoenemann** [comment]
> or the definition method return type should be change from Either<List<Location>, List<LocationLink>> to List<Either<Location, LocationLink>> (which by the way would be easier to process on client side).

I would also prefer the second variant, but after the discussion in #252 my impression was that staying as close as possible to the protocol definition is the preferred way.

**Comment by mickaelistria** [comment]
Indeed, staying close to protocol definition is preferred from server POV (no risk of generating erroneous messages) while the more flexible `List<Either<X, Y>>` is preferred from consumer POV. But I agree with most people in #252, sticking to the protocol is more sustainable, even if it makes some code a bit more annoying to write.
So it seems like the only solution is to improve the EitherTypeAdapter to specifically handle the cast of an empty array when both sides of the Either are collections.

**Comment by spoenemann** [comment]
I could fix this later this week, but I think it's too late for 2019-03?

https://wiki.eclipse.org/SimRel/2019-03/Simultaneous_Release_Plan

**Comment by mickaelistria** [comment]
Yes, it's too late. But the world will survive it.
