### ISSUE TITLE
Provide documentation for language client / Duplicate RPC method workspace/applyEdit.

### ISSUE THREAD

**Issue by Sciss** [eclipse/lsp4j#313]
Hello. There is no documentation on how to create a language client. The file https://github.com/eclipse/lsp4j/blob/master/documentation/README.md only refers to a server implemention. I'm trying to do the symmetric thing for client:

```scala
import java.util.concurrent.CompletableFuture

import org.eclipse.lsp4j.launch.LSPLauncher
import org.eclipse.lsp4j.services.LanguageClient
import org.eclipse.lsp4j.{MessageActionItem, MessageParams, PublishDiagnosticsParams, ShowMessageRequestParams}

object LanguageClientTest {
  case class Config()

  def main(args: Array[String]): Unit = {
    run(Config())
  }

  def run(config: Config): Unit = {
    val in        = System.in
    val out       = System.out
    val launcher  = LSPLauncher.createClientLauncher(new Client(config), in, out)
    launcher
  }

  class Client(config: Config) extends LanguageClient {
    def telemetryEvent(obj: Any): Unit = ???

    def publishDiagnostics(diagnostics: PublishDiagnosticsParams): Unit = ???

    def showMessage(messageParams: MessageParams): Unit = ???

    def showMessageRequest(requestParams: ShowMessageRequestParams): CompletableFuture[MessageActionItem] = ???

    def logMessage(message: MessageParams): Unit = ???
  }
}
```

The result is this:

```
Exception in thread "main" java.lang.IllegalStateException: Duplicate RPC method workspace/applyEdit.
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.lambda$getSupportedMethods$0(ServiceEndpoints.java:113)
	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:66)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:365)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:376)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:307)
	at org.eclipse.lsp4j.launch.LSPLauncher.createClientLauncher(LSPLauncher.java:106)
	at LanguageClientTest$.run(LanguageClientTest.scala:21)
```
Is this a bug?

**Comment by spoenemann** [comment]
It's probably a Scala-specific problem. This works fine in Java:

```
public class LanguageClientTest {
	@Test
	public void run() {
		InputStream in = System.in;
		OutputStream out = System.out;
		LSPLauncher.createClientLauncher(new Client(), in, out);
	}
	
	static class Client implements LanguageClient {
		@Override
		public void telemetryEvent(Object object) {}
		@Override
		public void publishDiagnostics(PublishDiagnosticsParams diagnostics) {}
		@Override
		public void showMessage(MessageParams messageParams) {}
		@Override
		public void logMessage(MessageParams message) {}
		@Override
		public CompletableFuture<MessageActionItem> showMessageRequest(ShowMessageRequestParams requestParams) {
			return CompletableFuture.completedFuture(new MessageActionItem("Foo"));
		}
	}
}
```

**Comment by olafurpg** [comment]
@Sciss This is a Scala problem, I've encountered the same problem extending `LanguageServer`. We work around it in Metals by declaring the annotations directly on the local service implementation
```scala
class MetalsLanguageServer { // no "extends LanguageServer"
  @JsonRequest("initialize")
  def initialize(params: InitializeParams): CompletableFuture[InitializeResult] = ???
}
```
This approach has also bought us flexibility in for example letting notifications return `CompletableFuture[Unit]`, which has been handy for testing notification handlers that trigger background tasks.
