### ISSUE TITLE
java.lang.annotation.AnnotationTypeMismatchException

### ISSUE THREAD

**Issue by Huxpro** [eclipse/lsp4j#322]
Are there any way to debug this? 
I assume I annotated something wrong by not extending `LanguageServer` after #321 
The error log is not helpful at all.

```
[info] Running test.languageserver.Main 
Starting server
[error] (run-main-11) java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract boolean org.eclipse.lsp4j.jsonrpc.services.JsonRequest.useSegment() (Found data of type class java.lang.Integer[0])
[error] java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract boolean org.eclipse.lsp4j.jsonrpc.services.JsonRequest.useSegment() (Found data of type class java.lang.Integer[0])
[error] 	at sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:57)
[error] 	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:84)
[error] 	at com.sun.proxy.$Proxy81.useSegment(Unknown Source)
[error] 	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.createRequestInfo(AnnotationUtil.java:97)
[error] 	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.createMethodInfo(AnnotationUtil.java:80)
[error] 	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:64)
[error] 	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
[error] 	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
[error] 	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:340)
[error] 	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:351)
[error] 	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:275)
[error] 	at test.languageserver.Main$.startServer(Main.scala:43)
[error] 	at test.languageserver.Main$.$anonfun$main$1(Main.scala:22)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withOut(Console.scala:167)
[error] 	at test.languageserver.Main$.main(Main.scala:22)
[error] 	at test.languageserver.Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by Dedefer** [comment]
same problem

**Comment by spoenemann** [comment]
Looks like a Scala-specific issue. Could you try with specific values for all annotation parameters, e.g. `@JsonRequest(value="textDocument/completion", useSegment = false)`?
