### ISSUE TITLE
\r\n causes NumberFormatException from StreamMessageProducer?

### ISSUE THREAD

**Issue by Huxpro** [eclipse/lsp4j#323]
```
Start the server!
Content-Length: 44\r\n
\r\n
{
  "jsonrpc": "2.0",
  "method": "exit"
}Jun 09, 2019 2:14:22 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: For input string: "44\r\n"
java.lang.NumberFormatException: For input string: "44\r\n"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.parseHeader(StreamMessageProducer.java:119)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:86)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I am trying to test the server from CLI. It seems like `\r\n` will be mis-interpreted as the number part of `Content-Length` of header? And without `\r\n` the server seems do nothing.

FYI I am testing with the template server from [LSP4J_Tutorial (I also raise an issue there)](https://github.com/LucasBullen/LSP4J_Tutorial/issues/3)

```java
public void exit() {
  System.out.println("Exit!");
}
```

But didn't see `Exit!` outputted.

So In general, what's the correct format to test the server from executable? 

Thanks ;)

**Comment by Huxpro** [comment]
close in favor of https://github.com/microsoft/language-server-protocol/issues/771
