### ISSUE TITLE
ConcurrentModificationException during MessageJsonHandler.toString()

### ISSUE THREAD

**Issue by mniewrzal** [eclipse/lsp4j#38]
Error is thrown when `MessageJsonHandler` is trying to display completion result (`CompletionList`):
```
Dec 15, 2016 11:01:08 AM org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor run
SEVERE: null
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:98)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:1)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.write(MessageTypeAdapterFactory.java:217)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapterFactory$Adapter.write(MessageTypeAdapterFactory.java:1)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at com.google.gson.Gson.toJson(Gson.java:603)
	at com.google.gson.Gson.toJson(Gson.java:583)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.toString(MessageJsonHandler.java:93)
	at org.eclipse.lsp4j.jsonrpc.messages.Message.toString(Message.java:29)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.logServerError(ProjectSpecificLanguageServerWrapper.java:267)
	at org.eclipse.lsp4e.ProjectSpecificLanguageServerWrapper.lambda$2(ProjectSpecificLanguageServerWrapper.java:238)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
I'm using latest master.

**Comment by spoenemann** [comment]
I don't see this problem with invocations of `Message.toString()` in a single-threaded test. Could it be that your `ProjectSpecificLanguageServerWrapper` is modifying the message instance from another thread during the `toString()` call?

**Comment by mniewrzal** [comment]
Yes, you are right. I forgot that CompletionList.getItems() list is sorted directly a moment after receiving the message. Thanks for help!
