### ISSUE TITLE
NullPointerException in RemoteEndpoint.java:214

### ISSUE THREAD

**Issue by smarter** [eclipse/lsp4j#48]
I have a WIP language-server (I could put it online if it would help but it might be somewhat difficult to setup), I'm testing it with vscode 1.8.1 and I sometimes end up triggering this:
```java
[error] janv. 11, 2017 4:26:47 PM org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor run
[error] GRAVE: null
[error] java.lang.NullPointerException
[error]         at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:214)
[error]         at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:138)
[error]         at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
[error]         at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
[error]         at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] 
```
Even if I'm doing something wrong here (any idea what that might be?), I assume that the code should handle errors gracefully and not crash.

**Comment by smarter** [comment]
Ah indeed it was my fault: I had `setCompletionProvider(new CompletionOptions)` in `initiliaze` but had overriden the `completion` method to return `null`.
