### ISSUE TITLE
Update ServerCapabilities to support work done progress

### ISSUE THREAD

**Issue by pisv** [eclipse/lsp4j#480]
Some of the  Server Capabilities need to be updated to support work done progress (e.g. `ServerCapabilities.getReferencesProvider()` must return `Either<Boolean, ReferenceOptions>` instead of `Boolean`).

**Comment by pisv** [comment]
Full list of server capabilities to update:

* `callHierarchyProvider`?: `boolean` | `CallHierarchyOptions` | `CallHierarchyRegistrationOptions`
* `declarationProvider`?: `boolean` | `DeclarationOptions` | `DeclarationRegistrationOptions`
* `definitionProvider`?: `boolean` | `DefinitionOptions`
* `documentFormattingProvider`?: `boolean` | `DocumentFormattingOptions`
* `documentHighlightProvider`?: `boolean` | `DocumentHighlightOptions`
* `documentRangeFormattingProvider`?: `boolean` | `DocumentRangeFormattingOptions`
* `documentSymbolProvider`?: `boolean` | `DocumentSymbolOptions`
* `hoverProvider`?: `boolean` | `HoverOptions`
* `implementationProvider`?: `boolean` | `ImplementationOptions` | `ImplementationRegistrationOptions`
* `referencesProvider`?: `boolean` | `ReferenceOptions`
* `selectionRangeProvider`?: `boolean` | `SelectionRangeOptions` | `SelectionRangeRegistrationOptions`
* `typeDefinitionProvider`?: `boolean` | `TypeDefinitionOptions` | `TypeDefinitionRegistrationOptions`
* `typeHierarchyProvider` (probably)
* `workspaceSymbolProvider`?: `boolean` | `WorkspaceSymbolOptions`

Also, some of the `*Options` classes need to be updated to support work done progress:

* `CodeLensRegistrationOptions`
* `ColorProviderOptions`
* `CompletionRegistrationOptions`
* `DocumentLinkOptions` and `DocumentLinkRegistrationOptions`
* `FoldingRangeProviderOptions`
* `RenameOptions`

And some `*Options` classes seem to be missing:

* `CodeActionRegistrationOptions`
* ` DocumentFormattingOptions` and `DocumentFormattingRegistrationOptions`
* `DocumentRangeFormattingOptions` and `DocumentRangeFormattingRegistrationOptions`
* `SelectionRangeOptions` and `SelectionRangeRegistrationOptions`
* `TypeHierarchyOptions` and `TypeHierarchyRegistrationOptions` (probably)

**Comment by nixel2007** [comment]
Small tip:
looks like some setters in serverCapabilities don't use concrete *Options classes at all.
For example, `setCallHierarchyProvider` takes `StaticRegistrationOptions` and neither `CallHierarchyRegistrationOptions` or `CallHierarchyOptions`.
callHierarchyProvider.
`setSelectionRangeProvider` also takes `StaticRegistrationOptions` instead of `SelectionRangeOptions` or `SelectionRangeRegistrationOptions`.
/cc @KamasamaK

**Comment by pisv** [comment]
Some of the items in the list have already been addressed, I have checked them off. I'm going to provide a PR for the rest.

**Comment by jcompagner** [comment]
i am not sure, i can create a new case but it seems this is the one i hit when i do this:

https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java#L52

there i enable experimental ivy stuff, i add the following command arg:

commands.add("--experimental-ivy");

if i do that then i get a lot of exceptions:

feb. 25, 2021 8:37:19 P.M. org.eclipse.lsp4j.jsonrpc.RemoteEndpoint logIssues
WARNING: Issue found in NotificationMessage: Message could not be parsed.
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Kind of progress notification is empty
	at com.google.gson.Gson.fromJson(Gson.java:947)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.fromJson(MessageTypeAdapter.java:329)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.parseParams(MessageTypeAdapter.java:249)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:119)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:55)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:119)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:853)
Caused by: com.google.gson.stream.MalformedJsonException: Kind of progress notification is empty
	at org.eclipse.lsp4j.adapters.WorkDoneProgressNotificationAdapter.createNotification(WorkDoneProgressNotificationAdapter.java:111)
	at org.eclipse.lsp4j.adapters.WorkDoneProgressNotificationAdapter.read(WorkDoneProgressNotificationAdapter.java:97)
	at org.eclipse.lsp4j.adapters.WorkDoneProgressNotificationAdapter.read(WorkDoneProgressNotificationAdapter.java:37)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 15 more

this is because the json message is:

{"jsonrpc":"2.0","method":"$/progress","params":{"token":"ngcc","value":{"done":false,"configFilePath":"c:/Users/jcomp/git/servoy_master/servoy-eclipse/com.servoy.eclipse.ngclient.ui/node/tsconfig.json","message":"Running ngcc for project c:/Users/jcomp/git/servoy_master/servoy-eclipse/com.servoy.eclipse.ngclient.ui/node/tsconfig.json"}}}

that code in 
org.eclipse.lsp4j.adapters.WorkDoneProgressNotificationAdapter.read(WorkDoneProgressNotificationAdapter.java

can't handle that 
the quick fix would be i think that we also in the switch:

switch (name) {

have a case

case "done": {
  if (in.nextBoolean()) kind = "report";
  else kind = "end";
  break;
}

at least i think we get a "done": "false" and a "done": "true" with then a message?

**Comment by pisv** [comment]
> i am not sure, i can create a new case but it seems this is the one i hit

I don't think it is related to this issue. Probably you hit #479.

**Comment by jonahgraham** [comment]
Hi folks, this issue was previously identified as being part of LSP4J 0.11.0 as it provided part of the support for completing LSP 3.16.0. If this is a non-blocking issue for 0.11.0 release, please update/remove milestone so that we can progress with the LSP4J 0.11.0 release soon. We can have a 0.12.0 release soon after the 0.11.0 release if there is value in that. In the absence of feedback I will remove the milestone in a few days so that we can release 0.11.0 as many consumers are waiting on an official LSP4J 0.11.0 release. Thank you.
