### ISSUE TITLE
Reflection in ServiceEndpoints.toServiceObject doesn't work in OSGi.

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lsp4j#5]
Some classloading usage doesn't work in OSGi world and prevents from using LSP4J in Eclipse plugins:

```
java.lang.IllegalArgumentException: interface org.eclipse.lsp4j.services.TextDocumentService is not visible from class loader
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.toServiceObject(ServiceEndpoints.java:32)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.lambda$new$1(EndpointProxy.java:44)
	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findDelegateSegments(AnnotationUtil.java:29)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.<init>(EndpointProxy.java:43)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.toServiceObject(ServiceEndpoints.java:32)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createIoLauncher(Launcher.java:124)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createLauncher(Launcher.java:72)
	at org.eclipse.lsp4j.jsonrpc.Launcher.createLauncher(Launcher.java:45)
	at org.eclipse.lsp4j.launch.LSPLauncher.createClientLauncher(LSPLauncher.java:29)
```

**Comment by mickaelistria** [comment]
Thanks. What's the publication policy of snapshot builds? Can I expect the new snapshot from master to be available automatically in the few minutes after pushing content?

**Comment by spoenemann** [comment]
You should see a new build triggered here a few minutes after content was pushed:
http://services.typefox.io/open-source/jenkins/job/lsp4j/

However, this does not include snapshot publishing. Those are updated once every night.

**Comment by mickaelistria** [comment]
Thanks. I still see no new buyild on http://services.typefox.io/open-source/jenkins/job/lsp4j/ . What's the value for "a few" minutes?

**Comment by svenefftinge** [comment]
The change hook doesn't seem to work yet. I triggered it manually.
