### ISSUE TITLE
Exception while parsing valid FileOperationPattern object

### ISSUE THREAD

**Issue by ceronman** [eclipse/lsp4j#526]
When trying the newly released `0.11.0` version as a client for the the [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) server, I'm getting the following exception right after calling `server.initialize()`:

```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
	at com.company.Main.main(Main.java:56)
Caused by: org.eclipse.lsp4j.jsonrpc.MessageIssueException: Message could not be parsed.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponseIssues(RemoteEndpoint.java:358)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handle(RemoteEndpoint.java:317)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:198)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

This works fine on version `0.10.0`, it only breaks in the new `0.11.0` update.

The exception itself doesn't provide much information, but after debugging at `MessageTypeAdapter`, I found the real cause of the parsing error:

```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 983 path $.result.capabilities.workspace.fileOperations.willRename.filters[0].pattern.matches
```

The json message returned by the server is this:

```
{"jsonrpc":"2.0","id":"1","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"selectionRangeProvider":true,"hoverProvider":true,"completionProvider":{"triggerCharacters":[":","."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite"],"resolveProvider":true},"codeLensProvider":{"resolveProvider":true},"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"=","moreTriggerCharacter":[".",">"]},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"workspace":{"fileOperations":{"willRename":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.rs","matches":"file"}},{"scheme":"file","pattern":{"glob":"**","matches":"folder"}}]}}},"callHierarchyProvider":true,"semanticTokensProvider":{"legend":{"tokenTypes":["comment","keyword","string","number","regexp","operator","namespace","type","struct","class","interface","enum","enumMember","typeParameter","function","method","property","macro","variable","parameter","angle","attribute","boolean","brace","bracket","builtinType","characterLiteral","comma","colon","dot","escapeSequence","formatSpecifier","generic","constParameter","lifetime","label","parenthesis","punctuation","selfKeyword","semicolon","typeAlias","union","unresolvedReference"],"tokenModifiers":["documentation","declaration","definition","static","abstract","deprecated","readonly","constant","controlFlow","injected","mutable","consuming","unsafe","attribute","callable"]},"range":true,"full":{"delta":true}},"experimental":{"joinLines":true,"ssr":true,"onEnter":true,"parentModule":true,"runnables":{"kinds":["cargo"]}}},"serverInfo":{"name":"rust-analyzer","version":"7435b9e"}}}
```

Zooming in to the exact location where the error happens:

```
..."pattern":{"glob":"**/*.rs","matches":"file"}}...
                                         ^
                                         |
                                         Error happens here
```

I decided to check the [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_willCreateFiles) to see if there was a problem with rust-analyzer, but it looks correct:

```
export type FileOperationPatternKind = 'file' | 'folder';
```

So it seems that the problem is on the LSP4J side.

I'm including a very simple program that reproduces the issue. It doesn't use `rust-analyzer` directly, just does a very basic emulation using streams. When running this program with LSP4J `0.10.0` it works fine. With `0.11.0` I get the mentioned exception.

[Main.java.zip](https://github.com/eclipse/lsp4j/files/6191893/Main.java.zip)

**Comment by KamasamaK** [comment]
Can you try with the latest snapshot? #523 might have fixed this.

**Comment by ceronman** [comment]
This is indeed fixed by #523. I just tested with the latest snapshot.

**Comment by cdietrich** [comment]
do we need a . release for this?

**Comment by jonahgraham** [comment]
:-) GitHub does not notify about "reactions" - I can now see that many people have +1ed a release with this fix so I will schedule one for sometime soon. See #521 and the lsp4j-dev mailing list.
