### ISSUE TITLE
LSPLauncher.createClientLauncher: IllegalStateException: Duplicate RPC method window/showDocument

### ISSUE THREAD

**Issue by Sciss** [eclipse/lsp4j#556]
Hi there,

I'm updating an older project from lsp4j 0.7.0 to 0.12.0, now at launch:

```scala
  private val launcher: Launcher[LanguageServer] = LSPLauncher.createClientLauncher(this, metalsOut, metalsIn)
```

 I am getting this error:

```
java.lang.IllegalStateException: Duplicate RPC method window/showDocument.
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.lambda$getSupportedMethods$0(ServiceEndpoints.java:113)
	at org.eclipse.lsp4j.jsonrpc.services.AnnotationUtil.findRpcMethods(AnnotationUtil.java:66)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:90)
	at org.eclipse.lsp4j.jsonrpc.services.ServiceEndpoints.getSupportedMethods(ServiceEndpoints.java:82)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.getSupportedMethods(Launcher.java:413)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.createJsonHandler(Launcher.java:335)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:319)
	at org.eclipse.lsp4j.launch.LSPLauncher.createClientLauncher(LSPLauncher.java:106)
	at dotterweide.metals.MetalsActor.<init>(MetalsActor.scala:117)
```

I don't see how that method would be duplicate, or what I'm doing wrong. Any help appreciated. I am working in Scala 2.13 (with the intent to add Scala 3 as well).

[Here](https://github.com/dotterweide/dotterweide-exp-metals/blob/1faf91471b9501754e70b5b35a0a63c058048c83/src/main/scala/dotterweide/metals/MetalsActor.scala) is the language client in question.

**Comment by cdietrich** [comment]
Did you debug the exception in serviceendpoints ?

**Comment by Sciss** [comment]
If I check what goes to `acceptor.accept(methodInfo)`, these are the pairs of `method` and `methodInfo.name`, until the point where the duplicate name is detected:

```
public default void org.eclipse.lsp4j.services.LanguageServer.cancelProgress(org.eclipse.lsp4j.WorkDoneProgressCancelParams)
window/workDoneProgress/cancel

public abstract void org.eclipse.lsp4j.services.LanguageServer.exit()
exit

public abstract java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageServer.shutdown()
shutdown

public default void org.eclipse.lsp4j.services.LanguageServer.initialized(org.eclipse.lsp4j.InitializedParams)
initialized

public abstract java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageServer.initialize(org.eclipse.lsp4j.InitializeParams)
initialize

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.declaration(org.eclipse.lsp4j.DeclarationParams)
textDocument/declaration

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.resolveCompletionItem(org.eclipse.lsp4j.CompletionItem)
completionItem/resolve

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.signatureHelp(org.eclipse.lsp4j.SignatureHelpParams)
textDocument/signatureHelp

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.hover(org.eclipse.lsp4j.HoverParams)
textDocument/hover

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.definition(org.eclipse.lsp4j.DefinitionParams)
textDocument/definition

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.typeDefinition(org.eclipse.lsp4j.TypeDefinitionParams)
textDocument/typeDefinition

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.implementation(org.eclipse.lsp4j.ImplementationParams)
textDocument/implementation

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.documentHighlight(org.eclipse.lsp4j.DocumentHighlightParams)
textDocument/documentHighlight

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.completion(org.eclipse.lsp4j.CompletionParams)
textDocument/completion

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.references(org.eclipse.lsp4j.ReferenceParams)
textDocument/references

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.documentSymbol(org.eclipse.lsp4j.DocumentSymbolParams)
textDocument/documentSymbol

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.codeAction(org.eclipse.lsp4j.CodeActionParams)
textDocument/codeAction

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.resolveCodeAction(org.eclipse.lsp4j.CodeAction)
codeAction/resolve

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.codeLens(org.eclipse.lsp4j.CodeLensParams)
textDocument/codeLens

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.resolveCodeLens(org.eclipse.lsp4j.CodeLens)
codeLens/resolve

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.formatting(org.eclipse.lsp4j.DocumentFormattingParams)
textDocument/formatting

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.rangeFormatting(org.eclipse.lsp4j.DocumentRangeFormattingParams)
textDocument/rangeFormatting

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.onTypeFormatting(org.eclipse.lsp4j.DocumentOnTypeFormattingParams)
textDocument/onTypeFormatting

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.linkedEditingRange(org.eclipse.lsp4j.LinkedEditingRangeParams)
textDocument/linkedEditingRange

public abstract void org.eclipse.lsp4j.services.TextDocumentService.didOpen(org.eclipse.lsp4j.DidOpenTextDocumentParams)
textDocument/didOpen

public abstract void org.eclipse.lsp4j.services.TextDocumentService.didChange(org.eclipse.lsp4j.DidChangeTextDocumentParams)
textDocument/didChange

public abstract void org.eclipse.lsp4j.services.TextDocumentService.didClose(org.eclipse.lsp4j.DidCloseTextDocumentParams)
textDocument/didClose

public abstract void org.eclipse.lsp4j.services.TextDocumentService.didSave(org.eclipse.lsp4j.DidSaveTextDocumentParams)
textDocument/didSave

public default void org.eclipse.lsp4j.services.TextDocumentService.willSave(org.eclipse.lsp4j.WillSaveTextDocumentParams)
textDocument/willSave

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.willSaveWaitUntil(org.eclipse.lsp4j.WillSaveTextDocumentParams)
textDocument/willSaveWaitUntil

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.documentLink(org.eclipse.lsp4j.DocumentLinkParams)
textDocument/documentLink

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.documentLinkResolve(org.eclipse.lsp4j.DocumentLink)
documentLink/resolve

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.documentColor(org.eclipse.lsp4j.DocumentColorParams)
textDocument/documentColor

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.colorPresentation(org.eclipse.lsp4j.ColorPresentationParams)
textDocument/colorPresentation

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.foldingRange(org.eclipse.lsp4j.FoldingRangeRequestParams)
textDocument/foldingRange

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.prepareRename(org.eclipse.lsp4j.PrepareRenameParams)
textDocument/prepareRename

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.typeHierarchy(org.eclipse.lsp4j.TypeHierarchyParams)
textDocument/typeHierarchy

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.resolveTypeHierarchy(org.eclipse.lsp4j.ResolveTypeHierarchyItemParams)
typeHierarchy/resolve

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.prepareCallHierarchy(org.eclipse.lsp4j.CallHierarchyPrepareParams)
textDocument/prepareCallHierarchy

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.callHierarchyIncomingCalls(org.eclipse.lsp4j.CallHierarchyIncomingCallsParams)
callHierarchy/incomingCalls

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.callHierarchyOutgoingCalls(org.eclipse.lsp4j.CallHierarchyOutgoingCallsParams)
callHierarchy/outgoingCalls

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.selectionRange(org.eclipse.lsp4j.SelectionRangeParams)
textDocument/selectionRange

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.semanticTokensFull(org.eclipse.lsp4j.SemanticTokensParams)
textDocument/semanticTokens/full

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.semanticTokensFullDelta(org.eclipse.lsp4j.SemanticTokensDeltaParams)
textDocument/semanticTokens/full/delta

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.semanticTokensRange(org.eclipse.lsp4j.SemanticTokensRangeParams)
textDocument/semanticTokens/range

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.moniker(org.eclipse.lsp4j.MonikerParams)
textDocument/moniker

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.TextDocumentService.rename(org.eclipse.lsp4j.RenameParams)
textDocument/rename

public abstract void org.eclipse.lsp4j.services.WorkspaceService.didChangeWatchedFiles(org.eclipse.lsp4j.DidChangeWatchedFilesParams)
workspace/didChangeWatchedFiles

public default void org.eclipse.lsp4j.services.WorkspaceService.didChangeWorkspaceFolders(org.eclipse.lsp4j.DidChangeWorkspaceFoldersParams)
workspace/didChangeWorkspaceFolders

public default void org.eclipse.lsp4j.services.WorkspaceService.didRenameFiles(org.eclipse.lsp4j.RenameFilesParams)
workspace/didRenameFiles

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.WorkspaceService.willCreateFiles(org.eclipse.lsp4j.CreateFilesParams)
workspace/willCreateFiles

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.WorkspaceService.executeCommand(org.eclipse.lsp4j.ExecuteCommandParams)
workspace/executeCommand

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.WorkspaceService.willDeleteFiles(org.eclipse.lsp4j.DeleteFilesParams)
workspace/willDeleteFiles

public default void org.eclipse.lsp4j.services.WorkspaceService.didDeleteFiles(org.eclipse.lsp4j.DeleteFilesParams)
workspace/didDeleteFiles

public abstract void org.eclipse.lsp4j.services.WorkspaceService.didChangeConfiguration(org.eclipse.lsp4j.DidChangeConfigurationParams)
workspace/didChangeConfiguration

public default void org.eclipse.lsp4j.services.WorkspaceService.didCreateFiles(org.eclipse.lsp4j.CreateFilesParams)
workspace/didCreateFiles

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.WorkspaceService.willRenameFiles(org.eclipse.lsp4j.RenameFilesParams)
workspace/willRenameFiles

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.WorkspaceService.symbol(org.eclipse.lsp4j.WorkspaceSymbolParams)
workspace/symbol

public abstract void org.eclipse.lsp4j.services.LanguageClient.logMessage(org.eclipse.lsp4j.MessageParams)
window/logMessage

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.showDocument(org.eclipse.lsp4j.ShowDocumentParams)
window/showDocument

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.createProgress(org.eclipse.lsp4j.WorkDoneProgressCreateParams)
window/workDoneProgress/create

public default void org.eclipse.lsp4j.services.LanguageClient.notifyProgress(org.eclipse.lsp4j.ProgressParams)
$/progress

public default void org.eclipse.lsp4j.services.LanguageClient.logTrace(org.eclipse.lsp4j.LogTraceParams)
$/logTrace

public default void org.eclipse.lsp4j.services.LanguageClient.setTrace(org.eclipse.lsp4j.SetTraceParams)
$/setTrace

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.refreshSemanticTokens()
workspace/semanticTokens/refresh

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.refreshCodeLenses()
workspace/codeLens/refresh

public abstract void org.eclipse.lsp4j.services.LanguageClient.telemetryEvent(java.lang.Object)
telemetry/event

public abstract void org.eclipse.lsp4j.services.LanguageClient.publishDiagnostics(org.eclipse.lsp4j.PublishDiagnosticsParams)
textDocument/publishDiagnostics

public abstract void org.eclipse.lsp4j.services.LanguageClient.showMessage(org.eclipse.lsp4j.MessageParams)
window/showMessage

public abstract java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.showMessageRequest(org.eclipse.lsp4j.ShowMessageRequestParams)
window/showMessageRequest

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.applyEdit(org.eclipse.lsp4j.ApplyWorkspaceEditParams)
workspace/applyEdit

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.registerCapability(org.eclipse.lsp4j.RegistrationParams)
client/registerCapability

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.unregisterCapability(org.eclipse.lsp4j.UnregistrationParams)
client/unregisterCapability

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.workspaceFolders()
workspace/workspaceFolders

public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.configuration(org.eclipse.lsp4j.ConfigurationParams)
workspace/configuration

public java.util.concurrent.CompletableFuture dotterweide.metals.MetalsActor.showDocument(org.eclipse.lsp4j.ShowDocumentParams)
window/showDocument
```

so that reflection based sweep sees

```
public default java.util.concurrent.CompletableFuture org.eclipse.lsp4j.services.LanguageClient.showDocument(org.eclipse.lsp4j.ShowDocumentParams)
```
followed by
```
public java.util.concurrent.CompletableFuture dotterweide.metals.MetalsActor.showDocument(org.eclipse.lsp4j.ShowDocumentParams)
```
(I am not even overrriding `showDocument`)

**Comment by Sciss** [comment]
> (I am not even overrriding showDocument)

Huh. I just tried adding

```scala
  override def showDocument(params: ShowDocumentParams): CompletableFuture[ShowDocumentResult] =
    super.showDocument(params)
```
that moves the error to another method `window/workDoneProgress/create`.

Seems a problem with the reflection based scanning being too intimately tight to how Java compiles. In general, reflection is always a bit of a recipe for disaster. I will try not overriding _every_ method to see if that fixes it for Scala.

**Comment by Sciss** [comment]
Yes, overriding all interface methods seems to be doing the trick

```scala
 override def showDocument(params: ShowDocumentParams): CompletableFuture[ShowDocumentResult] =
    super.showDocument(params)

  override def createProgress(params: WorkDoneProgressCreateParams): CompletableFuture[Void] =
    super.createProgress(params)

  override def notifyProgress(params: ProgressParams): Unit =
    super.notifyProgress(params)

  override def logTrace(params: LogTraceParams): Unit =
    super.logTrace(params)

  override def setTrace(params: SetTraceParams): Unit =
    super.setTrace(params)

  override def refreshSemanticTokens(): CompletableFuture[Void] =
    super.refreshSemanticTokens()

  override def refreshCodeLenses(): CompletableFuture[Void] =
    super.refreshCodeLenses()
```

**Comment by jonahgraham** [comment]
Have a look at #321 it is similar AFAICT

**Comment by Sciss** [comment]
Yes, it seems to be the same issue, closing thus.
