### ISSUE TITLE
java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by gastaldi** [eclipse/lsp4j#633]
Related issue: https://github.com/redhat-developer/intellij-quarkus/issues/583 
```

org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:122)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:275)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
	... 6 more
```

**Comment by pisv** [comment]
May be related to #585

**Comment by cdietrich** [comment]
i think its too late for eclipse 2022-06.

**Comment by jonahgraham** [comment]
> Any chance of having a release soon? This error is really annoying in IntelliJ

Depends on your context - snapshots are published for each commit. There is no release scheduled though. How are you consuming LSP4J?

**Comment by pisv** [comment]
I wonder whether this issue is caused by Quarkus in the first place. Why the input stream gets closed while the loop in `StreamMessageProducer.listen` is still running? There was a somewhat similar case in #585, where the socked closed exception was logged because the socket had been closed by the language client before stopping the loop. If so, a fix on the Quarkus side might solve the problem entirely.
