### ISSUE TITLE
Incompatibility with vscode-languageclient 3.0

### ISSUE THREAD

**Issue by smarter** [eclipse/lsp4j#71]
Using https://github.com/Microsoft/vscode-languageserver-node/tree/master/client 3.0.4:
```java
févr. 21, 2017 3:32:04 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
AVERTISSEMENT: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {}
}
java.lang.IllegalArgumentException: wrong number of arguments
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:46)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:87)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:165)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:136)
        at org.eclipse.lsp4j.jsonrpc.Launcher.lambda$null$0(Launcher.java:59)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I think lsp4j expects the `initialized` message to have its `params` entry undefined but instead it's set to `{}`.

**Comment by akosyakov** [comment]
@smarter I think that vscode client should not sent params at all [here](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L1229), similar to [exit notification](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L179); otherwise [the protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#new-initialized-notification) should be updated.

**Comment by smarter** [comment]
Arguably yes, but having lsp4j treat `params: {}` and `params: undefined` the same way shouldn't hurt.

**Comment by akosyakov** [comment]
@svenefftinge do you think we should try to handle it? like try to match method with and without params object

**Comment by svenefftinge** [comment]
I think we should not bail but just log with warning level, that the argument is going to be ignored.
